---
title: "Econ HW2"
author: "Kristin Gill and Alyssa Kibbe"
date: "4/14/2021"
output: 
   html_document:
     code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(janitor)
library(here)
```

```{r}
# read in the data
water_data <- read_csv(here("data", "HW2_Water.csv")) %>% 
  clean_names()
```

## 1. 
### Agriculture
P = 1.9 + 0.51(abatement)
```{r}
ggplot(data = water_data, aes(x = reduced_water_use_abatement,
                              y = mc_agriculture)) +
  geom_line(colour = "blue") +
  labs(x = "Abatement (Acre Feet)",
       y = "Price ($/Acre Feet)",
       title = "Agriculture Marginal Cost of Water Use Abatement") +
  theme_minimal() +
  geom_smooth(method = "lm",
              color = "black",
              size = 0.5,
              fill = "gray10",
              alpha = 0.5) +
  ggpubr::stat_regline_equation(label.x = 115, label.y = 0)
```

### Meat
P = 9.5 + 0.38(abatement)
```{r}
ggplot(data = water_data, aes(x = reduced_water_use_abatement,
                              y = mc_meat)) +
  geom_line(colour = "blue") +
  labs(x = "Abatement (Acre Feet)",
       y = "Price ($/Acre Feet)",
       title = "Meat Marginal Cost of Water Use Abatement") +
  theme_minimal() +
  geom_smooth(method = "lm",
              color = "black",
              size = 0.5,
              fill = "gray10",
              alpha = 0.5) +
  ggpubr::stat_regline_equation(label.x = 115, label.y = 0)
```


### Industrial
P = -27 + 1.1(abatement)
```{r}
ggplot(data = water_data, aes(x = reduced_water_use_abatement,
                              y = mc_industrial)) +
  geom_line(colour = "blue") +
  labs(x = "Abatement (Acre Feet)",
       y = "Price ($/Acre Feet)",
       title = "Inudustrial Marginal Cost of Water Use Abatement") +
  theme_minimal() +
  geom_smooth(method = "lm",
              color = "black",
              size = 0.5,
              fill = "gray10",
              alpha = 0.5) +
  ggpubr::stat_regline_equation(label.x = 115, label.y = 0)
```


### Urban
P = -14 + 0.6(abatement)
```{r}
ggplot(data = water_data, aes(x = reduced_water_use_abatement,
                              y = mc_urban)) +
  geom_line(colour = "blue") +
  labs(x = "Abatement (Acre Feet)",
       y = "Price ($/Acre Feet)",
       title = "Urban Marginal Cost of Water Use Abatement") +
  theme_minimal() +
  geom_smooth(method = "lm",
              color = "black",
              size = 0.5,
              fill = "gray10",
              alpha = 0.5) +
  ggpubr::stat_regline_equation(label.x = 115, label.y = 0)
```

## 2. 
### Agriculture
```{r}
ag_df <- data.frame(abatement = seq.int(from = 0, to = 170)) %>% 
  mutate(price = 1.9 + (0.51*abatement)) %>% 
  mutate(quantity = 170 - abatement)

ggplot(data = ag_df, aes(x = quantity,
                         y = price)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Quantity(Acre Feet)",
       y = "Price ($/Acre Feet)",
       title = "Agriculture Sector Demand for Water Use") +
  ggpubr::stat_regline_equation(label.x = 25, label.y = 5)
```

### Meat
```{r}
meat_df <- data.frame(abatement = seq.int(from = 0, to = 200)) %>% 
  mutate(price = 9.5 + (0.38*abatement)) %>% 
  mutate(quantity = 200 - abatement)

ggplot(data = meat_df, aes(x = quantity,
                         y = price)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Quantity(Acre Feet)",
       y = "Price ($/Acre Feet)",
       title = "Meat Sector Demand for Water Use") +
  ggpubr::stat_regline_equation(label.x = 25, label.y = 5)
```

### Industrial
```{r}
industrial_df <- data.frame(abatement = seq.int(from = 0, to = 230)) %>% 
  mutate(price = -27 + (1.1*abatement)) %>% 
  mutate(quantity = 230 - abatement)

ggplot(data = industrial_df, aes(x = quantity,
                                 y = price)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Quantity(Acre Feet)",
       y = "Price ($/Acre Feet)",
       title = "Industrial Sector Demand for Water Use") +
  ggpubr::stat_regline_equation(label.x = 25, label.y = 5)
```

### Urban
```{r}
urban_df <- data.frame(abatement = seq.int(from = 0, to = 300)) %>% 
  mutate(price = -14 + (0.6*abatement)) %>% 
  mutate(quantity = 300 - abatement)

ggplot(data = urban_df, aes(x = quantity,
                         y = price)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Quantity(Acre Feet)",
       y = "Price ($/Acre Feet)",
       title = "Urban Sector Demand for Water Use") +
  ggpubr::stat_regline_equation(label.x = 25, label.y = 5)
```
The industrial sector is willing to pay the most ($230) for the first unit 
